drop type if exists pub_set_indicators_table
create type pub_set_indicators_table as table
(
	pub_block_begin int not null,
	pub_block_end int not null,
	pub_set_no1 varchar(max) null,
	pub_set_no2 varchar(max) null,
	pub_set_no3 varchar(max) null,
	p float not null,
	mcs float null,
	mncs float null,
	pp_top_n_cits float null,
	pp_top_prop float null,
	pp_uncited float null,
	mjs float null,
	mnjs float null,
	mjpp_top_n_cits float null,
	mjpp_top_prop float null,
	mjpp_uncited float null,
	prop_self_cits float null,
	int_cov float null,
	n_refs float null,
	n_refs_covered float null,
	pp_collab float null,
	pp_int_collab float null,
	pp_industry float null,
	mgcd float null,
	pp_short_dist_collab float null,
	pp_long_dist_collab float null,
	pp_oa float null,
	pp_gold_oa float null,
	pp_hybrid_oa float null,
	pp_bronze_oa float null,
	pp_green_oa float null,
	pp_oa_unknown float null
)
